### ISSUE TITLE
Copryight notice

### ISSUE THREAD

**Issue by LeagueRaINi** [CastCodes/VAC#1]
**We kindly suggest you remove our code from your respository, which was taken from our binary on [Thunderstore](https://valheim.thunderstore.io/package/CodeWizards/AntiCheat/) without any changes whatsoever.
Not only did u fail to credit us (without asking for permission anyways) but you also released under a more permissive license, furthermore breaking copright laws.**

### The code in question:
* https://github.com/CastCodes/VAC/tree/main/VAC/AntiMods

**Comment by J-Pster** [comment]
I developed this plugin together with a friend of mine, he who did the anti-mods part, he had said he knew how to do it.
I will remove it just in case.

Code part removed.

**Comment by J-Pster** [comment]
@LeagueRaINi I have sent you an e-mail, when you can, please reply to me.
